Repository sis0n/LibSys, pull requests merged in 2025-09, with the labels that each got.

#5 Setup/tailwind and other css variables
  .gitignore
  package-lock.json
  package.json
  public/css/index.css
  public/css/input.css
  public/css/output.css
  src/Views/auth/login.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.php
Labels: feature, style, setup

#10 fix merge conflict
  public/index.php
Labels: fix

#11 Feat: header footer
  assets/library-icons/apple-touch-icon.png
  assets/ucc-icons/apple-touch-icon.png
  public/css/output.css
  public/index.php
  src/Controllers/UserController.php
  src/Core/Controller.php
  src/Views/auth/login.php
  src/Views/dashboard/student.php
  src/Views/errors/403.php
  src/Views/errors/404.php
  src/Views/partials/footer.php
  src/Views/partials/header.php
Labels: feature, style

#21 Feat: Sidebar Navigation For All Accounts
  public/css/output.css
  src/Config/RouteConfig.php
  src/Controllers/authController.php
  src/Controllers/dashboardController.php
  src/Controllers/sidebarController.php
  src/Core/Controller.php
  src/Views/Admin/attendanceLogs.php
  src/Views/Admin/backupAndRestore.php
  src/Views/Admin/bookManagement.php
  src/Views/Admin/borrowingHistory.php
  src/Views/Admin/dashboard.php
  src/Views/Admin/equipmentManagement.php
  src/Views/Admin/features.php
  src/Views/Admin/globalLogs.php
  src/Views/Admin/overdueAlert.php
  src/Views/Admin/userManagement.php
  src/Views/Librarian/attendanceLogs.php
  src/Views/Librarian/backupAndRestore.php
  src/Views/Librarian/bookManagement.php
  src/Views/Librarian/borrowingHistory.php
  src/Views/Librarian/dashboard.php
  src/Views/Librarian/equipmentManagement.php
  src/Views/Librarian/features.php
  src/Views/Librarian/globalLogs.php
  src/Views/Librarian/overdueAlert.php
  src/Views/Librarian/userManagement.php
  src/Views/Student/bookCatalog.php
  src/Views/Student/borrowingHistory.php
  src/Views/Student/dashboard.php
  src/Views/Student/equipmentCatalog.php
  src/Views/Student/myAttendance.php
  src/Views/Student/myCart.php
  src/Views/Student/qrBorrowingTicket.php
  src/Views/SuperAdmin/attendanceLogs.php
  src/Views/SuperAdmin/backupAndRestore.php
  src/Views/SuperAdmin/bookManagement.php
  src/Views/SuperAdmin/borrowingHistory.php
  src/Views/SuperAdmin/dashboard.php
  src/Views/SuperAdmin/equipmentManagement.php
  src/Views/SuperAdmin/features.php
  src/Views/SuperAdmin/globalLogs.php
  src/Views/SuperAdmin/overdueAlert.php
  src/Views/SuperAdmin/userManagement.php
  src/Views/dashboard/admin.php
  src/Views/dashboard/librarian.php
  src/Views/dashboard/student.php
  src/Views/dashboard/superAdmin.php
  src/Views/partials/header.php
  src/Views/partials/sidebar.php
Labels: feature, chore, style

#30 Feat: Add the QR Code Scanner & Top Visitor in librarian, admin, superadmin
  public/css/output.css
  src/Config/RouteConfig.php
  src/Controllers/sidebarController.php
  src/Views/Admin/qrScanner.php
  src/Views/Admin/topVisitor.php
  src/Views/Librarian/qrScanner.php
  src/Views/Librarian/topVisitor.php
  src/Views/SuperAdmin/qrScanner.php
  src/Views/SuperAdmin/topVisitor.php
  src/Views/partials/sidebar.php
Labels: feature, style

#31 Initial: attendance design
  public/css/input.css
  public/css/output.css
  src/Config/RouteConfig.php
  src/Controllers/authController.php
  src/Controllers/scannerController.php
  src/Models/user.php
  src/Views/Admin/attendanceLogs.php
  src/Views/Librarian/attendanceLogs.php
  src/Views/SuperAdmin/attendanceLogs.php
  src/Views/scanner/attendance.php
Labels: feature, chore, style, setup

#37 bug: manual attendance not working.
  src/Controllers/scannerController.php
  src/Repositories/attendanceRepository.php
  src/Repositories/userRepository.php
Labels: bug, fix

#39 feat: inventory for books
  docs/Collection_Main_Campus_Library_final.csv
  docs/edited_file.php
  docs/library_db.md
  docs/step_by_step_import_db.md
  docs/update_queries.md
  src/Config/RouteConfig.php
  src/Controllers/bookController.php
  src/Models/book.php
  src/Repositories/bookRepository.php
Labels: feature

#45 bug: route for my QR sidebar and QR borrow ticket
  src/Config/RouteConfig.php
Labels: bug

#60 Feat: my cart design
  public/css/output.css
  src/Views/Student/myCart.php
Labels: chore, style

#74 bug: sidebar book catalog design
  src/Config/RouteConfig.php
Labels: bug, chore, fix

#76 bug: book available counts
  src/Config/RouteConfig.php
  src/Controllers/bookController.php
  src/Repositories/bookRepository.php
  src/Views/Student/bookCatalog.php
Labels: bug

#65 Enhance: No record default state if no records found.
  public/css/output.css
  src/Views/Admin/attendanceLogs.php
  src/Views/Librarian/attendanceLogs.php
  src/Views/SuperAdmin/attendanceLogs.php
Labels: enhancement, style

#70 Chore: Overflowing Sidebar in (Super Admin, Admin, and Librarian)
  public/css/output.css
  src/Controllers/sidebarController.php
  src/Core/Controller.php
  src/Views/partials/sidebar.php
Labels: bug, chore

#78 Chore, remove the c in year column of csv file
  docs/Collection_Main_Campus_Library_final.csv
Labels: documentation, chore

#80 chore: update the books table year column
  docs/update_queries.md
Labels: chore
